# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ye Chan Kim
email: yechan77@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  There is a legend that the name of the best CS student
  in the world is written somewhere in this website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ykim160.github.io/" # the base hostname & protocol for your site
github_username: ykim160

# Build settings
markdown: kramdown
